# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
permissions:
  contents: read
  pull-request: write

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Info
      run: |
        echo "Ref: ${{ github.ref_name }}"

    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Test
      run: |
        cd cloud
        go test

    - name: Test Build
      run: ./build.sh


    - name: Build All
      if: startsWith(github.ref, 'refs/tags/')
      run: ./build.sh all

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/*
        tag_name: ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
        overwrite: true
